### ISSUE TITLE
bug in art description paragraph

### ISSUE THREAD

**Issue by JaiNatha** [Himalayan-Academy/hamsa#19]
When no art description in available is displays an "i"

as seen here:
http://dev.himalayanacademy.com/hamsa/#/item/ce5b67291ceb356a2f8538b525092c23

This instead needs to just display a blank space or something.

**Comment by soapdog** [comment]
This is not a bug, that image really has "i" as its description in the exif data:

![ssh _mnt_c_users_soapdog_prog_ssbc_scuttle-shell_node_modules_systray_traybin 2018-08-23 13 57 32](https://user-images.githubusercontent.com/23247/44540237-9e151d80-a6dc-11e8-8528-095cdf24a81b.png)

HAMSA doesn't alter exif data, so that is coming like this from dinodia or the volunteers who are adding the metadata.
