### ISSUE TITLE
FullScreen Navigation Buttons - Design Update

### ISSUE THREAD

**Issue by JaiNatha** [Himalayan-Academy/hamsa#25]
Sorry to do this to you, but Paramacharya wanted to redesign the 4 main buttons. Here is what he wants it to look like, with each button being the same color. The dropdowns can remain the same apart from the text colors all being made #783441. The little styled yellow line below it in this image is actually green and is an svg which I'll provide. I'll send it via slack. 
![hamsa design](https://user-images.githubusercontent.com/25754228/44431495-d0d2e080-a539-11e8-8714-bf144e3f3e1d.jpg)

**Comment by soapdog** [comment]
@JaiNatha that might take some hours here. I am working on it now.

**Comment by soapdog** [comment]
It is actually moving faster than I thought.

![image](https://user-images.githubusercontent.com/23247/44545640-028ba900-a6ec-11e8-9f61-de91843b0734.png)

Be aware that with these changes, the other views without a hero (which I call the _slim header views_) become this:

![image](https://user-images.githubusercontent.com/23247/44545714-32d34780-a6ec-11e8-8ffc-4ed9876b4ef6.png)

If this result is OK, then we're basically done with this issue. Oh, and even though on the mockup you sent me, the _search_ placeholder is with the same style as the other text, the browser insists on hardcoding a little transparency to those placeholders.

Also, due to how the HTML is laid out, it was easier to remove the white space on the sides of the hero image because trying to color the background of the menus and keeping their start and end aligned was difficult. The menus span the whole page, they are centered but their div goes from side to side. I thought it looked better filling the whole space and that it might look better if we prepare a hero that is shorter.

**Comment by soapdog** [comment]
Hummm... maybe that top and bottom padding on the menus can be reduced, let me try.

**Comment by soapdog** [comment]
Yes, it is much better with _20 px_ instead of _40 px_.

![image](https://user-images.githubusercontent.com/23247/44546066-387d5d00-a6ed-11e8-97eb-3e9c1061ff73.png)

**Comment by soapdog** [comment]
@JaiNatha I've deployed a new version with these changes. I'd like feedback if it is good for shipping before closing this task.

**Comment by JaiNatha** [comment]
Ok. Let's knock the padding down further, to 12px.

After that this issue is closed

**Comment by soapdog** [comment]
Made the changes, will close the issue after I deploy a new version.

**Comment by soapdog** [comment]
deployed new version
