### ISSUE TITLE
Admin Editor: Select Image / Change Tag to Collections

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/hamsa#54]
- [x] Change "New Tag" to "Add New Collection"
 - [x] Change "Add Tag" to "Assign"
 - [x] on the backend: prepend the string with "Collections " ; 
- [x] add the tags to the select images; 
- [x]  update Collection list;  refresh page

**Comment by Brahmanathaswami** [comment]
![2020-02-07_03-17-05](https://user-images.githubusercontent.com/3675722/74033496-5af34c80-495a-11ea-919b-62f5d1dfe874.png)

**Comment by soapdog** [comment]
Had to change the way this work. Originally you could select many collections using the checkboxes and then add them all at once to the images on the left. The problem is that adding a collection changes the checksum of the image, so after adding the first collection, we didn't had the checksum to use for adding the next collection. So, I changed them to radio buttons, you select one and click add. It will refresh the data after adding and then you can select another and click again.
